name = "CUDD"
uuid = "345a2cc7-28d8-58b2-abdf-cff77ea7d7f1"
version = "0.2.1"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
BinaryProvider = "0.5"
CEnum = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
